POST http://localhost:8080/api/to-do
Content-Type: application/json
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MSwiaWF0IjoxNjg3MDE1MDEwLCJleHAiOjE2ODcwMTU2MTB9.ZhgR6TXDTkR-mNZNoV44zetGmxXCckzDX6x-2bEDWUo
{
    "user_id":"1",
    "name":"test1",
    "start_time":"00.00.00",
    "end_time":"23.59.59",
    "date":"2023-05-22",
    "level":3,
    "completed":0
}      
###

PUT http://localhost:8080/api/to-do/201
Content-Type: application/json
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MSwiaWF0IjoxNjg3MDE1MDEwLCJleHAiOjE2ODcwMTU2MTB9.ZhgR6TXDTkR-mNZNoV44zetGmxXCckzDX6x-2bEDWUo

{
    "name":"Have",
    "start_time":"00:00:00",
    "end_time":"23:59:59",
    "date":"2023-05-22",
    "level":2,
    "completed":1
}

###
DELETE http://localhost:8080/api/to-do/201
Content-Type: application/json
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2ODQ3MjM0OTcsImV4cCI6MTY4NDcyNDA5N30.XDvOIr79dIhQM1VycP1WL3cfg-4qGeNh0KwHh9zQNn4

###
GET http://localhost:8080/api/to-do?user_id=1&date=2023-05-22
Content-Type: application/json
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MSwiaWF0IjoxNjg3MDE1MDEwLCJleHAiOjE2ODcwMTU2MTB9.ZhgR6TXDTkR-mNZNoV44zetGmxXCckzDX6x-2bEDWUo
