
POST http://localhost:8080/api/workspace
Content-Type: application/json
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2ODQ3MjAyNjksImV4cCI6MTY4NDcyMDg2OX0.-zWqVpiCEnFsKgujn3iJXtGmyoA5cnKGsfSr0XKx2dc

{
    "user_id":"1",
    "name":"Hoeee"
}      

###

GET http://localhost:8080/api/workspace?user_id=1
Content-Type: application/json

###
DELETE http://localhost:8080/api/workspace/10

### 
PUT http://localhost:8080/api/workspace/1
Content-Type: application/json

{
    "name":"Home"
}

###
